export const EXAM_LIST_REQUEST = "EXAM_LIST_REQUEST"
export const EXAM_LIST_SUCCESS = "EXAM_LIST_SUCCESS"
export const EXAM_LIST_FAIL = "EXAM_LIST_FAIL"

export const GET_EXAM_REQUEST = "GET_EXAM_REQUEST"
export const GET_EXAM_SUCCESS = "GET_EXAM_SUCCESS"
export const GET_EXAM_FAIL = "GET_EXAM_FAIL"
