export const EXAM_LIST_REQUEST = "EXAM_LIST_REQUEST";
export const EXAM_LIST_SUCCESS = "EXAM_LIST_SUCCESS";
export const EXAM_LIST_FAIL = "EXAM_LIST_FAIL";

export const GET_EXAM_REQUEST = "GET_EXAM_REQUEST";
export const GET_EXAM_SUCCESS = "GET_EXAM_SUCCESS";
export const GET_EXAM_FAIL = "GET_EXAM_FAIL";

export const CREATE_EXAM_REQUEST = "CREATE_EXAM_REQUEST";
export const CREATE_EXAM_SUCCESS = "CREATE_EXAM_SUCCESS";
export const CREATE_EXAM_FAIL = "CREATE_EXAM_FAIL";
export const CREATE_EXAM_RESET = "CREATE_EXAM_RESET"

export const GET_EXAM_LIST_BY_STUDENT_REQUEST =
  "GET_EXAM_LIST_BY_STUDENT_REQUEST";
export const GET_EXAM_LIST_BY_STUDENT_SUCCESS =
  "GET_EXAM_LIST_BY_STUDENT_SUCCESS";
export const GET_EXAM_LIST_BY_STUDENT_FAIL = "GET_EXAM_LIST_BY_STUDENT_FAIL";

export const DELETE_EXAM_REQUEST = "DELETE_EXAM_REQUEST"
export const DELETE_EXAM_SUCCESS = "DELETE_EXAM_SUCCESS"
export const DELETE_EXAM_FAIL = "DELETE_EXAM_FAIL"
export const DELETE_EXAM_RESET = "DELETE_EXAM_RESET"
