export const LECTURER_LOGIN_REQUEST = "LECTURER_LOGIN_REQUEST"
export const LECTURER_LOGIN_SUCCESS = "LECTURER_LOGIN_SUCCESS"
export const LECTURER_LOGIN_FAIL = "LECTURER_LOGIN_FAIL"
export const LECTURER_LOGOUT = "LECTURER_LOGOUT"

export const UPDATE_LECTURER_INFO_REQUEST ="UPDATE_LECTURER_INFO_REQUEST"
export const UPDATE_LECTURER_INFO_SUCCESS ="UPDATE_LECTURER_INFO_SUCCESS"
export const UPDATE_LECTURER_INFO_FAIL ="UPDATE_LECTURER_INFO_FAIL"
export const UPDATE_LECTURER_INFO_RESET ="UPDATE_LECTURER_INFO_RESET"
