export const LECTURER_LOGIN_REQUEST = "LECTURER_LOGIN_REQUEST"
export const LECTURER_LOGIN_SUCCESS = "LECTURER_LOGIN_SUCCESS"
export const LECTURER_LOGIN_FAIL = "LECTURER_LOGIN_FAIL"
export const LECTURER_LOGOUT = "LECTURER_LOGOUT"
