export const QUESTION_LIST_REQUEST = "QUESTION_LIST_REQUEST";
export const QUESTION_LIST_SUCCESS = "QUESTION_LIST_SUCCESS";
export const QUESTION_LIST_FAIL = "QUESTION_LIST_FAIL";

export const QUESTION_REQUEST = "QUESTION_REQUEST";
export const QUESTION_SUCCESS = "QUESTION_SUCCESS";
export const QUESTION_FAIL = "QUESTION_FAIL";

export const QUESTION_CREATE_REQUEST = "QUESTION_CREATE_REQUEST";
export const QUESTION_CREATE_SUCCESS = "QUESTION_CREATE_SUCCESS";
export const QUESTION_CREATE_FAIL = "QUESTION_CREATE_FAIL";
export const QUESTION_CREATE_RESET = "QUESTION_CREATE_RESET";

export const QUESTION_LIST_BY_SUBJECT_REQUEST =
  "QUESTION_LIST_BY_SUBJECT_REQUEST";
export const QUESTION_LIST_BY_SUBJECT_SUCCESS =
  "QUESTION_LIST_BY_SUBJECT_SUCCESS";
export const QUESTION_LIST_BY_SUBJECT_FAIL = "QUESTION_LIST_BY_SUBJECT_FAIL";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST"
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS"
export const DELETE_QUESTION_FAIL = "DELETE_QUESTION_FAIL"
export const DELETE_QUESTION_RESET = "DELETE_QUESTION_RESET"
