export const QUESTION_LIST_REQUEST = "QUESTION_LIST_REQUEST";
export const QUESTION_LIST_SUCCESS = "QUESTION_LIST_SUCCESS";
export const QUESTION_LIST_FAIL = "QUESTION_LIST_FAIL";

export const QUESTION_REQUEST = "QUESTION_REQUEST";
export const QUESTION_SUCCESS = "QUESTION_SUCCESS";
export const QUESTION_FAIL = "QUESTION_FAIL";

export const QUESTION_CREATE_REQUEST = "QUESTION_CREATE_REQUEST";
export const QUESTION_CREATE_SUCCESS = "QUESTION_CREATE_SUCCESS";
export const QUESTION_CREATE_FAIL = "QUESTION_CREATE_FAIL";
export const QUESTION_CREATE_RESET = "QUESTION_CREATE_RESET";
