export const SUBJECT_LIST_REQUEST = "SUBJECT_LIST_REQUEST";
export const SUBJECT_LIST_SUCCESS = "SUBJECT_LIST_SUCCESS";
export const SUBJECT_LIST_FAIL = "SUBJECT_LIST_FAIL";

export const SUBJECT_DETAIL_LIST_REQUEST = "SUBJECT_DETAIL_LIST_REQUEST";
export const SUBJECT_DETAIL_LIST_SUCCESS = "SUBJECT_DETAIL_LIST_SUCCESS";
export const SUBJECT_DETAIL_LIST_FAIL = "SUBJECT_DETAIL_LIST_FAIL";
