export const POST_SUBMITTION_REQUEST = "POST_SUBMITTION_REQUEST";
export const POST_SUBMITTION_SUCESS = "POST_SUBMITTION_SUCCESS";
export const POST_SUBMITTION_FAIL = "POST_SUBMITTION_FAIL";

export const GET_STUDENT_SUBMITTIONS_REQUEST = "GET_STUDENT_SUBMITTIONS_REQUEST"
export const GET_STUDENT_SUBMITTIONS_SUCCESS = "GET_STUDENT_SUBMITTIONS_SUCCESS"
export const GET_STUDENT_SUBMITTIONS_FAIL = "GET_STUDENT_SUBMITTIONS_FAIL"
